fix(voxel_grid_downsample_filter): don't use deprecated PCL header (#1069)
pcl/io/io.h is deprecated since 2011. Use the current location of the
file.

This fixes the following build error on my system with PCL 1.15.1:

    /build/autoware_core-release-release-jazzy-autoware_downsample_filters-1.8.0-1/src/voxel_grid_downsample_filter/voxel_grid_downsample_filter_node.cpp:24:10:
    fatal error: pcl/io/io.h: No such file or directory
       24 | #include <pcl/io/io.h>
          |          ^~~~~~~~~~~~~

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>
Signed-off-by: Mert Yavuz <mert@adastec.com>