fix(autoware_trajectory): add missing include
std::clamp() added in #791 needs to include <algorithm>. Without it,
GCC 14 complains with "error: 'clamp' is not a member of 'std'".

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>