fix(mission_planner): unused using-declaration with GCC 15
```
[ 53%] Building CXX object CMakeFiles/autoware_mission_planner_component.dir/src/mission_planner/mission_planner.cpp.o
/build/autoware_core-release-release-humble-autoware_mission_planner-1.7.0-2/src/mission_planner/mission_planner.cpp: In constructor 'autoware::mission_planner::MissionPlanner::MissionPlanner(const rclcpp::NodeOptions&)':
/build/autoware_core-release-release-humble-autoware_mission_planner-1.7.0-2/src/mission_planner/mission_planner.cpp:49:28: error: unused using-declaration 'std::placeholders::_2' [-Werror=unused-variable]
   49 |   using std::placeholders::_2;
      |                            ^~
```

Signed-off-by: Guilhem Saurel <guilhem.saurel@laas.fr>