fix(autoware_trajectory): Switch to libexpected-dev
Recent update [1] to the Humble distribution deprecated the vendored version of
tl_expected, leading to the compiler warning. Since the package is compiled with
-Werror=cpp, this leads to the following build failure:

    In file included from /build/autoware_core-release-release-humble-autoware_trajectory-1.7.0-2/include/autoware/trajectory/interpolator/result.hpp:18,
                     from /build/autoware_core-release-release-humble-autoware_trajectory-1.7.0-2/include/autoware/trajectory/interpolator/detail/interpolator_common_interface.hpp:18,
                     from /build/autoware_core-release-release-humble-autoware_trajectory-1.7.0-2/include/autoware/trajectory/interpolator/interpolator.hpp:18,
                     from /build/autoware_core-release-release-humble-autoware_trajectory-1.7.0-2/include/autoware/trajectory/point.hpp:19,
                     from
                     /build/autoware_core-release-release-humble-autoware_trajectory-1.7.0-2/src/point.cpp:15:
    /ros-humble-tl-expected-1.3.0-r1/include/tl_expected/expected.hpp:21:2: error: #warning "tl_expected/expected.hpp is
    deprecated and will be removed by the ROS 2 Lyrical Luth release. Use <tl/expected.hpp> from libexpected-dev, or
    <rcpputils/tl_expected/expected.hpp> if the system header is not available." [-Werror=cpp]
       21 | #warning \
          |  ^~~~~~~

This switches the implementation to system-provided version of the library, as
recommended.

[1]: https://github.com/ros/rosdistro/pull/50850

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>